import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Header from "@/component/Header/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="fr">
			<body>
				<Header />
				{children}
				<ToastContainer />
			</body>
		</html>
	);
}
